name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lighthouse Check
        uses: foo-software/lighthouse-check-action@v9.1.1
        with:
          commentUrl: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
          gitHubAccessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
          prCommentEnabled: true
          urls: 'https://md-share.vercel.app,https://md-share.vercel.app/about,https://md-share.vercel.app/contact'
